<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>20b4309e-d111-4646-95dc-f2e485a02344</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AuditFramework.ApiService\AuditFramework.ApiService.csproj" />
    <ProjectReference Include="..\AuditFramework.Web\AuditFramework.Web.csproj" />
    <ProjectReference Include="..\AuditFramework.Worker\AuditFramework.Worker.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.5.0" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="9.5.0" />
  </ItemGroup>

</Project>
